auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
  filesystem:
    directory: /loki/chunks

limits_config:
  retention_period: 168h # 7 дней
  allow_structured_metadata: false
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  per_stream_rate_limit: 16MB
  per_stream_rate_limit_burst: 32MB
  max_global_streams_per_user: 10000
  max_line_size: 2MB
  max_query_series: 1000
  max_query_lookback: 168h
  max_query_length: 721h
  max_query_parallelism: 32
  cardinality_limit: 100000
  max_streams_per_user: 10000
  ingestion_rate_strategy: global

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h # 7 дней

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

common:
  path_prefix: /tmp/loki

ruler:
  alertmanager_url: http://alertmanager:9093
  enable_api: true
  enable_sharding: true
  ring:
    kvstore:
      store: inmemory
  rule_path: /loki/rules
  storage:
    type: local
    local:
      directory: /loki/rules
  wal:
    dir: /loki/wal
