server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    backoff_config:
      min_period: 1s
      max_period: 5s
    timeout: 10s
    batchwait: 1s
    batchsize: 1048576

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: [".*"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: "stream"
      - target_label: "job"
        replacement: "docker"
      - source_labels: ["__meta_docker_container_id"]
        target_label: "container_id"
      - source_labels: ["__meta_docker_container_name"]
        regex: "/mango_(.*)"
        target_label: "app"
        replacement: "mango"
      - source_labels: ["__meta_docker_container_name"]
        regex: "/player_(.*)"
        target_label: "app"
        replacement: "player"
    pipeline_stages:
      - regex:
          expression: 'level=(?P<level>\w+)\s+ts=(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d+Z)\s+caller=(?P<caller>[^\s]+)\s+msg="(?P<message>[^"]+)"'
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000000Z"
      - labels:
          level:
          caller:
      - output:
          source: message

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log

  - job_name: mango-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mango-app
          app: mango
          environment: production
          __path__: /usr/src/app/**/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            logger: logger
            function: function
            line: line
      - labels:
          level:
          logger:
          function:
          line:
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000000Z"

  - job_name: player-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: player-app
          app: player
          environment: production
          __path__: /usr/src/app/**/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            logger: logger
            function: function
            line: line
      - labels:
          level:
          logger:
          function:
          line:
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000000Z"
