server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    backoff_config:
      min_period: 1s
      max_period: 5s
    timeout: 10s
    batchwait: 1s
    batchsize: 1048576

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            log: log
            time: time
            attrs: attrs

      - labels:
          stream:

      - timestamp:
          source: time
          format: RFC3339Nano

      - match:
          selector: '{job="docker"}'
          stages:
            - json:
                expressions:
                  tag: attrs.tag
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>[A-Z]+)\]: (?P<logger>[^:]+)\((?P<line>\d+)\) - (?P<message>.*)$'
                source: log
            - labels:
                level:
                logger:
                line:
            - template:
                source: tag
                template: '{{ if contains .tag "mango-firefox" }}mango-firefox{{ end }}'
                action: replace
            - labels:
                service:

      - output:
          source: message

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log

  - job_name: mango-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mango-app
          app: mango
          environment: production
          __path__: /var/lib/docker/containers/*/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            logger: logger
            function: function
            line: line
      - labels:
          level:
          logger:
          function:
          line:
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000000Z"

  - job_name: player-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: player-app
          app: player
          environment: production
          __path__: /usr/src/app/**/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            logger: logger
            function: function
            line: line
      - labels:
          level:
          logger:
          function:
          line:
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000000000Z"
