global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      scheme: http
      timeout: 10s
      api_version: v2

rule_files:
  - "alert_rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "${HOSTNAME}"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "${HOSTNAME}"

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    basic_auth:
      username: "${grafana_admin_user}"
      password: "${grafana_admin_password}"

  - job_name: "docker"
    static_configs:
      - targets: ["node-exporter:9323"]
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "${HOSTNAME}"

  - job_name: "apps"
    static_configs:
      - targets:
          - "172.19.0.9:8000"
          - "player:8000"
    metrics_path: /metrics
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "mango"
        regex: "172.19.0.9.*"
      - source_labels: [__address__]
        target_label: app
        replacement: "mango"
        regex: "172.19.0.9.*"
      - source_labels: [__address__]
        target_label: container_id
        replacement: "${CONTAINER_ID}"
