{
 "title": "Application Logs",
 "tags": [
  "logs",
  "applications"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "label": "Application", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Info Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"mango-app\"} | json | level=~\"info|INFO\" | __error__=\"\""
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"mango-app\"} | json | level=~\"warning|WARNING\" | __error__=\"\""
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"mango-app\"} | json | level=~\"error|ERROR\" | __error__=\"\""
    }
   ]
  },
  {
   "title": "Debug Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"mango-app\"} | json | level=~\"debug|DEBUG\" | __error__=\"\""
    }
   ]
  }
 ]
}